
[     UTC     ] Logs for agent-jill-valentines.streamlit.app/
────────────────────────────────────────────────────────────────────────────────────────
[06:01:47] 🖥 Provisioning machine...
[06:01:47] 🎛 Preparing system...
[06:01:47] ⛓ Spinning up manager process...
[06:01:57] 🚀 Starting up repository: 'agent-jill', branch: 'main', main module: 'app.py'
[06:01:57] 🐙 Cloning repository...
[06:01:59] 🐙 Cloning into '/mount/src/agent-jill'...

[06:01:59] 🐙 Cloned repository!
[06:01:59] 🐙 Pulling code changes from Github...
[06:02:00] 📦 Processing dependencies...

──────────────────────────────────────── uv ───────────────────────────────────────────

Using uv pip install.
Using Python 3.13.9 environment at /home/adminuser/venv
  × No solution found when resolving dependencies:
  ╰─▶ Because only the following versions of numpy are available:
          numpy<=1.26.0
          numpy==1.26.1
          numpy==1.26.2
          numpy==1.26.3
          numpy==1.26.4
          numpy>2
      and pandas==2.1.3 depends on numpy>=1.26.0,<2, we can conclude that
      pandas==2.1.3 depends on numpy>=1.26.0,<=1.26.4.
      And because you require pandas==2.1.3 and numpy==1.24.3, we can conclude
      that your requirements are unsatisfiable.
Checking if Streamlit is installed
Installing rich for an improved exception logging
Using uv pip install.
Using Python 3.13.9 environment at /home/adminuser/venv
Resolved [2025-10-30 06:02:01.969205] 4 packages[2025-10-30 06:02:01.970113]  [2025-10-30 06:02:01.970503] in 153ms[2025-10-30 06:02:01.970860] 
Prepared 4 packages in 231ms
Installed 4 packages in 96ms
 + markdown-it-py==4.0.0
 + mdurl==0.1.2
 + pygments==2.19.2
 + rich==14.2.0

────────────────────────────────────────────────────────────────────────────────────────


──────────────────────────────────────── pip ───────────────────────────────────────────

Using standard pip install.
Collecting streamlit==1.28.1 (from -r /mount/src/agent-jill/requirements.txt (line 1))
  Downloading streamlit-1.28.1-py2.py3-none-any.whl.metadata (8.1 kB)
Collecting pandas==2.1.3 (from -r /mount/src/agent-jill/requirements.txt (line 2))
  Downloading pandas-2.1.3.tar.gz (4.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 58.7 MB/s eta 0:00:00[2025-10-30 06:02:05.100925] 
  Installing build dependencies: started
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [218 lines of output]
      + meson setup /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3 /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/.mesonpy-u4y4kw4f/build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --vsenv --native-file=/tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/.mesonpy-u4y4kw4f/build/meson-python-native-file.ini
      The Meson build system
      Version: 1.2.1
      Source dir: /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3
      Build dir: /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/.mesonpy-u4y4kw4f/build
      Build type: native build
      Project name: pandas
      Project version: 2.1.3
      C compiler for the host machine: cc (gcc 12.2.0 "cc (Debian 12.2.0-14+deb12u1) 12.2.0")
      C linker for the host machine: cc ld.bfd 2.40
      C++ compiler for the host machine: c++ (gcc 12.2.0 "c++ (Debian 12.2.0-14+deb12u1) 12.2.0")
      C++ linker for the host machine: c++ ld.bfd 2.40
      Cython compiler for the host machine: cython (cython 0.29.37)
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Program python found: YES (/home/adminuser/venv/bin/python)
      Did not find pkg-config by name 'pkg-config'
      Found Pkg-config: NO
      Run-time dependency python found: YES 3.13
      Build targets in project: 53
      
      pandas 2.1.3
      
        User defined options
          Native files: /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/.mesonpy-u4y4kw4f/build/meson-python-native-file.ini
          buildtype   : release
          vsenv       : True
          b_ndebug    : if-release
          b_vscrt     : md
      
      Found ninja-1.13.0.git.kitware.jobserver-pipe-1 at /tmp/pip-build-env-e44lpz9z/normal/bin/ninja
      
      Visual Studio environment is needed to run Ninja. It is recommended to use Meson wrapper:
      /tmp/pip-build-env-e44lpz9z/overlay/bin/meson compile -C .
      + /tmp/pip-build-env-e44lpz9z/normal/bin/ninja
      [1/151] Generating pandas/_libs/khash_primitive_helper_pxi with a custom command
      [2/151] Generating pandas/_libs/algos_common_helper_pxi with a custom command
      [3/151] Generating pandas/_libs/index_class_helper_pxi with a custom command
      [4/151] Generating pandas/_libs/algos_take_helper_pxi with a custom command
      [5/151] Generating pandas/_libs/intervaltree_helper_pxi with a custom command
      [6/151] Generating pandas/_libs/sparse_op_helper_pxi with a custom command
      [7/151] Generating pandas/_libs/hashtable_func_helper_pxi with a custom command
      [8/151] Generating pandas/_libs/hashtable_class_helper_pxi with a custom command
      [9/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/tslibs/base.pyx
      [10/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/tslibs/ccalendar.pyx
      [11/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/tslibs/np_datetime.pyx
      [12/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/tslibs/dtypes.pyx
      [13/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/tslibs/offsets.pyx
      [14/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/tslibs/vectorized.pyx
      [15/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/indexing.pyx
      [16/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/tslibs/nattype.pyx
      [17/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/arrays.pyx
      [18/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/tslibs/strptime.pyx
      [19/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/tslibs/fields.pyx
      [20/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/hashing.pyx
      [21/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/tslibs/period.pyx
      [22/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/ops_dispatch.pyx
      [23/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/tslibs/parsing.pyx
      [24/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/properties.pyx
      [25/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/tslibs/timezones.pyx
      [26/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/ops.pyx
      [27/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/internals.pyx
      [28/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/missing.pyx
      [29/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/byteswap.pyx
      [30/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/lib.pyx
      [31/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/testing.pyx
      [32/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/tslibs/conversion.pyx
      [33/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/tslibs/tzconversion.pyx
      [34/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/parsers.pyx
      [35/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/tslibs/timedeltas.pyx
      [36/151] Compiling C object pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_base.pyx.c.o
      FAILED: [code=1] pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_base.pyx.c.o
      cc -Ipandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p -Ipandas/_libs/tslibs -I../../pandas/_libs/tslibs -I../../../../pip-build-env-e44lpz9z/overlay/lib/python3.13/site-packages/numpy/core/include -I../../pandas/_libs/include -I/usr/local/include/python3.13 -fvisibility=hidden -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -w -std=c99 -O3 -DNPY_NO_DEPRECATED_API=0 -DNPY_TARGET_VERSION=NPY_1_21_API_VERSION -fPIC -MD -MQ pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_base.pyx.c.o -MF pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_base.pyx.c.o.d -o pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_base.pyx.c.o -c pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c
      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c: In function ‘__Pyx_PyInt_As_long’:
      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c:5397:27: error: too few arguments to function ‘_PyLong_AsByteArray’
       5397 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,
            |                           ^~~~~~~~~~~~~~~~~~~
      In file included from /usr/local/include/python3.13/longobject.h:107,
                       from /usr/local/include/python3.13/Python.h:82,
                       from pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c:6:
      /usr/local/include/python3.13/cpython/longobject.h:111:17: note: declared here
        111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
            |                 ^~~~~~~~~~~~~~~~~~~
      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c: In function ‘__Pyx_PyInt_As_int’:
      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c:5631:27: error: too few arguments to function ‘_PyLong_AsByteArray’
       5631 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,
            |                           ^~~~~~~~~~~~~~~~~~~
      /usr/local/include/python3.13/cpython/longobject.h:111:17: note: declared here
        111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
            |                 ^~~~~~~~~~~~~~~~~~~
      [37/151] Compiling C object pandas/_libs/tslibs/dtypes.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_dtypes.pyx.c.o
      FAILED: [code=1] pandas/_libs/tslibs/dtypes.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_dtypes.pyx.c.o
      cc -Ipandas/_libs/tslibs/dtypes.cpython-313-x86_64-linux-gnu.so.p -Ipandas/_libs/tslibs -I../../pandas/_libs/tslibs -I../../../../pip-build-env-e44lpz9z/overlay/lib/python3.13/site-packages/numpy/core/include -I../../pandas/_libs/include -I/usr/local/include/python3.13 -fvisibility=hidden -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -w -std=c99 -O3 -DNPY_NO_DEPRECATED_API=0 -DNPY_TARGET_VERSION=NPY_1_21_API_VERSION -fPIC -MD -MQ pandas/_libs/tslibs/dtypes.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_dtypes.pyx.c.o -MF pandas/_libs/tslibs/dtypes.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_dtypes.pyx.c.o.d -o pandas/_libs/tslibs/dtypes.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_dtypes.pyx.c.o -c pandas/_libs/tslibs/dtypes.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/dtypes.pyx.c
      pandas/_libs/tslibs/dtypes.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/dtypes.pyx.c: In function ‘__Pyx_PyInt_As_enum____pyx_t_6pandas_5_libs_6tslibs_6dtypes_PeriodDtypeCode’:
      pandas/_libs/tslibs/dtypes.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/dtypes.pyx.c:16379:27: error: too few arguments to function ‘_PyLong_AsByteArray’
      16379 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,
            |                           ^~~~~~~~~~~~~~~~~~~
      In file included from /usr/local/include/python3.13/longobject.h:107,
                       from /usr/local/include/python3.13/Python.h:82,
                       from pandas/_libs/tslibs/dtypes.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/dtypes.pyx.c:6:
      /usr/local/include/python3.13/cpython/longobject.h:111:17: note: declared here
        111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
            |                 ^~~~~~~~~~~~~~~~~~~
      pandas/_libs/tslibs/dtypes.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/dtypes.pyx.c: In function ‘__Pyx_PyInt_As_npy_int64’:
      pandas/_libs/tslibs/dtypes.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/dtypes.pyx.c:16575:27: error: too few arguments to function ‘_PyLong_AsByteArray’
      16575 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,
            |                           ^~~~~~~~~~~~~~~~~~~
      /usr/local/include/python3.13/cpython/longobject.h:111:17: note: declared here
        111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
            |                 ^~~~~~~~~~~~~~~~~~~
      pandas/_libs/tslibs/dtypes.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/dtypes.pyx.c: In function ‘__Pyx_PyInt_As_NPY_DATETIMEUNIT’:
      pandas/_libs/tslibs/dtypes.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/dtypes.pyx.c:16923:27: error: too few arguments to function ‘_PyLong_AsByteArray’
      16923 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,
            |                           ^~~~~~~~~~~~~~~~~~~
      /usr/local/include/python3.13/cpython/longobject.h:111:17: note: declared here
        111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
            |                 ^~~~~~~~~~~~~~~~~~~
      pandas/_libs/tslibs/dtypes.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/dtypes.pyx.c: In function ‘__Pyx_PyInt_As_int’:
      pandas/_libs/tslibs/dtypes.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/dtypes.pyx.c:17195:27: error: too few arguments to function ‘_PyLong_AsByteArray’
      17195 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,
            |                           ^~~~~~~~~~~~~~~~~~~
      /usr/local/include/python3.13/cpython/longobject.h:111:17: note: declared here
        111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
            |                 ^~~~~~~~~~~~~~~~~~~
      pandas/_libs/tslibs/dtypes.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/dtypes.pyx.c: In function ‘__Pyx_PyInt_As_long’:
      pandas/_libs/tslibs/dtypes.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/dtypes.pyx.c:17429:27: error: too few arguments to function ‘_PyLong_AsByteArray’
      17429 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,
            |                           ^~~~~~~~~~~~~~~~~~~
      /usr/local/include/python3.13/cpython/longobject.h:111:17: note: declared here
        111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
            |                 ^~~~~~~~~~~~~~~~~~~
      [38/151] Compiling C object pandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_ccalendar.pyx.c.o
      FAILED: [code=1] pandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_ccalendar.pyx.c.o
      cc -Ipandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p -Ipandas/_libs/tslibs -I../../pandas/_libs/tslibs -I../../../../pip-build-env-e44lpz9z/overlay/lib/python3.13/site-packages/numpy/core/include -I../../pandas/_libs/include -I/usr/local/include/python3.13 -fvisibility=hidden -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -w -std=c99 -O3 -DNPY_NO_DEPRECATED_API=0 -DNPY_TARGET_VERSION=NPY_1_21_API_VERSION -fPIC -MD -MQ pandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_ccalendar.pyx.c.o -MF pandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_ccalendar.pyx.c.o.d -o pandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_ccalendar.pyx.c.o -c pandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/ccalendar.pyx.c
      pandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/ccalendar.pyx.c: In function ‘__Pyx_PyInt_As_int’:
      pandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/ccalendar.pyx.c:7376:27: error: too few arguments to function ‘_PyLong_AsByteArray’
       7376 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,
            |                           ^~~~~~~~~~~~~~~~~~~
      In file included from /usr/local/include/python3.13/longobject.h:107,
                       from /usr/local/include/python3.13/Python.h:82,
                       from pandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/ccalendar.pyx.c:6:
      /usr/local/include/python3.13/cpython/longobject.h:111:17: note: declared here
        111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
            |                 ^~~~~~~~~~~~~~~~~~~
      pandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/ccalendar.pyx.c: In function ‘__Pyx_PyInt_As_long’:
      pandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/ccalendar.pyx.c:7686:27: error: too few arguments to function ‘_PyLong_AsByteArray’
       7686 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,
            |                           ^~~~~~~~~~~~~~~~~~~
      /usr/local/include/python3.13/cpython/longobject.h:111:17: note: declared here
        111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
            |                 ^~~~~~~~~~~~~~~~~~~
      [39/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/tslibs/timestamps.pyx
      [40/151] Compiling C object pandas/_libs/tslibs/conversion.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_conversion.pyx.c.o
      FAILED: [code=1] pandas/_libs/tslibs/conversion.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_conversion.pyx.c.o
      cc -Ipandas/_libs/tslibs/conversion.cpython-313-x86_64-linux-gnu.so.p -Ipandas/_libs/tslibs -I../../pandas/_libs/tslibs -I../../../../pip-build-env-e44lpz9z/overlay/lib/python3.13/site-packages/numpy/core/include -I../../pandas/_libs/include -I/usr/local/include/python3.13 -fvisibility=hidden -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -w -std=c99 -O3 -DNPY_NO_DEPRECATED_API=0 -DNPY_TARGET_VERSION=NPY_1_21_API_VERSION -fPIC -MD -MQ pandas/_libs/tslibs/conversion.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_conversion.pyx.c.o -MF pandas/_libs/tslibs/conversion.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_conversion.pyx.c.o.d -o pandas/_libs/tslibs/conversion.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_conversion.pyx.c.o -c pandas/_libs/tslibs/conversion.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/conversion.pyx.c
      pandas/_libs/tslibs/conversion.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/conversion.pyx.c: In function ‘__Pyx_init_assertions_enabled’:
      pandas/_libs/tslibs/conversion.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/conversion.pyx.c:2448:105: error: invalid type argument of ‘->’ (have ‘int’)
       2448 |     __pyx_assertions_enabled_flag = ! _PyInterpreterState_GetConfig(__Pyx_PyThreadState_Current->interp)->optimization_level;
            |                                                                                                         ^~
      pandas/_libs/tslibs/conversion.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/conversion.pyx.c: In function ‘__Pyx_PyInt_As_NPY_DATETIMEUNIT’:
      pandas/_libs/tslibs/conversion.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/conversion.pyx.c:30972:27: error: too few arguments to function ‘_PyLong_AsByteArray’
      30972 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,
            |                           ^~~~~~~~~~~~~~~~~~~
      In file included from /usr/local/include/python3.13/longobject.h:107,
                       from /usr/local/include/python3.13/Python.h:82,
                       from pandas/_libs/tslibs/conversion.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/conversion.pyx.c:6:
      /usr/local/include/python3.13/cpython/longobject.h:111:17: note: declared here
        111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
            |                 ^~~~~~~~~~~~~~~~~~~
      pandas/_libs/tslibs/conversion.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/conversion.pyx.c: In function ‘__Pyx_PyInt_As_npy_int64’:
      pandas/_libs/tslibs/conversion.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/conversion.pyx.c:31168:27: error: too few arguments to function ‘_PyLong_AsByteArray’
      31168 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,
            |                           ^~~~~~~~~~~~~~~~~~~
      /usr/local/include/python3.13/cpython/longobject.h:111:17: note: declared here
        111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
            |                 ^~~~~~~~~~~~~~~~~~~
      pandas/_libs/tslibs/conversion.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/conversion.pyx.c: In function ‘__Pyx_PyInt_As_npy_int32’:
      pandas/_libs/tslibs/conversion.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/conversion.pyx.c:31516:27: error: too few arguments to function ‘_PyLong_AsByteArray’
      31516 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,
            |                           ^~~~~~~~~~~~~~~~~~~
      /usr/local/include/python3.13/cpython/longobject.h:111:17: note: declared here
        111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
            |                 ^~~~~~~~~~~~~~~~~~~
      pandas/_libs/tslibs/conversion.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/conversion.pyx.c: In function ‘__Pyx_PyInt_As_int’:
      pandas/_libs/tslibs/conversion.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/conversion.pyx.c:31911:27: error: too few arguments to function ‘_PyLong_AsByteArray’
      31911 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,
            |                           ^~~~~~~~~~~~~~~~~~~
      /usr/local/include/python3.13/cpython/longobject.h:111:17: note: declared here
        111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
            |                 ^~~~~~~~~~~~~~~~~~~
      pandas/_libs/tslibs/conversion.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/conversion.pyx.c: In function ‘__Pyx_PyInt_As_long’:
      pandas/_libs/tslibs/conversion.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/conversion.pyx.c:32107:27: error: too few arguments to function ‘_PyLong_AsByteArray’
      32107 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,
            |                           ^~~~~~~~~~~~~~~~~~~
      /usr/local/include/python3.13/cpython/longobject.h:111:17: note: declared here
        111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
            |                 ^~~~~~~~~~~~~~~~~~~
      pandas/_libs/tslibs/conversion.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/conversion.pyx.c: In function ‘__Pyx_PyInt_As_char’:
      pandas/_libs/tslibs/conversion.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/conversion.pyx.c:32341:27: error: too few arguments to function ‘_PyLong_AsByteArray’
      32341 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,
            |                           ^~~~~~~~~~~~~~~~~~~
      /usr/local/include/python3.13/cpython/longobject.h:111:17: note: declared here
        111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
            |                 ^~~~~~~~~~~~~~~~~~~
      [41/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/tslib.pyx
      [42/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/sas.pyx
      [43/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/index.pyx
      [44/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/window/indexers.pyx
      [45/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/writers.pyx
      [46/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/reshape.pyx
      [47/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/interval.pyx
      [48/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/window/aggregations.pyx
      [49/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/groupby.pyx
      [50/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/algos.pyx
      [51/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/sparse.pyx
      [52/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/hashtable.pyx
      [53/151] Compiling Cython source /tmp/pip-install-pfn9qyq9/pandas_242775ec41034cd0a3c89a99933bd9c3/pandas/_libs/join.pyx
      ninja: build stopped: subcommand failed.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: pip install --upgrade pip
Checking if Streamlit is installed
Installing rich for an improved exception logging
Using standard pip install.
Collecting rich>=10.14.0
  Downloading rich-14.2.0-py3-none-any.whl.metadata (18 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=10.14.0)
  Downloading markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich>=10.14.0)
  Downloading pygments-2.19.2-py3-none-any.whl.metadata (2.5 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=10.14.0)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading rich-14.2.0-py3-none-any.whl (243 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 243.4/243.4 kB 14.3 MB/s eta 0:00:00[2025-10-30 06:05:52.966804] 
Downloading markdown_it_py-4.0.0-py3-none-any.whl (87 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.3/87.3 kB 120.7 MB/s eta 0:00:00[2025-10-30 06:05:52.983922] 
Downloading pygments-2.19.2-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 78.7 MB/s eta 0:00:00[2025-10-30 06:05:53.010931] 
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: pygments, mdurl, markdown-it-py, rich
  Attempting uninstall: pygments
    Found existing installation: Pygments 2.19.2
    Uninstalling Pygments-2.19.2:
      Successfully uninstalled Pygments-2.19.2
  Attempting uninstall: mdurl
    Found existing installation: mdurl 0.1.2
    Uninstalling mdurl-0.1.2:
      Successfully uninstalled mdurl-0.1.2
  Attempting uninstall: markdown-it-py
    Found existing installation: markdown-it-py 4.0.0
    Uninstalling markdown-it-py-4.0.0:
      Successfully uninstalled markdown-it-py-4.0.0
  Attempting uninstall: rich
    Found existing installation: rich 14.2.0
    Uninstalling rich-14.2.0:
      Successfully uninstalled rich-14.2.0
Successfully installed markdown-it-py-4.0.0 mdurl-0.1.2 pygments-2.19.2 rich-14.2.0

[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: pip install --upgrade pip

────────────────────────────────────────────────────────────────────────────────────────

[06:05:55] ❗️ installer returned a non-zero exit code
[06:05:55] ❗️ Error during processing dependencies! Please fix the error and push an update, or try restarting the app.